server:
  port: 8085
  address: 0.0.0.0 
  forward-headers-strategy: framework

spring:
  profiles:
    include: secret  # 민감정보 secret 파일
   #active: dev  # 개발환경 dev 파일

  logging:
    level:
      project.comebackhomebe.domain: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
      org.hibernate.orm.jdbc.extract: TRACE
      org.springframework.transaction.interceptor: TRACE
      org.springdoc: DEBUG
      org.springframework: DEBUG
      org.springframework.messaging: DEBUG
      org.springframework.web.socket: DEBUG
      org.springframework.messaging.simp: DEBUG

springdoc:
  packages-to-scan: project.comebackhomebe.domain
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui/index.html
    url: /v3/api-docs
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

slack:
  webhook-uri: https://hooks.slack.com/services/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
  channel: "로그보내기"
  username : "임현성"

management:
  ## 액추에이터 info 상세 내역
  info:
    os:
      enabled: true
    java:
      enabled: true
    env:
      enabled: true

  ## 액추에이터 표시할 값들 설정
  endpoint:
    shutdown:
      enabled: true

    caches:
      enabled: false

    ## health 상세 내역 활성화
    health:
      show-details: always

  ## 액추에이터 web, jmx 설정
  endpoints:
    web:
      exposure:
        include: "*"  # 모든 활성화된 엔드포인트 포함
        exclude: # 개발 환경에서는 모두 노출을 시키지만 배포 환경에서는 예민 정보들을 exclude에 설정한다.
          - threaddump
          - heapdump
    jmx:
      exposure:
        include: "*"
        exclude:
          - threaddump
          - heapdump
  # 헬스에서 디스크 정보를 삭제
  health:
    diskspace:
      enabled: false

  httpexchanges:
    recording:
      enabled: true

## 애플리케이션 info 설정
info:
  organization:
    name: hyeonseong
  contact:
    email: admin@admin.kr
    phoneNumber: 010-xxxx-xxxx


logging:
  file:
    path: ./logs


external:
  api:
    uri: "https://cbh-ai.kro.kr"
