spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://34.44.154.211:3306/comebackhome?useSSL=false
    username: comebackhome
    password: .4[Pl{t"_l\5Y/LA
    driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    uris: http://elasticsearch:9200

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  data:
    redis:
      host: redis-refresh-token
      port: 6379
      password: 1234
      
    mongodb:
      uri: mongodb://root:root@mongo:27017/chat_app?authSource=admin


  cloud:
    gcp:
      storage:
        bucket: comebackhome-bucket

  google:
    redirect_uri: "https://cbh.kro.kr/login/oauth2/code/google"
