spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  data:
    redis:
      host: redis-refresh-token
      port: 6379
      password: 1234

  cloud:
    gcp:
      storage:
        bucket: comebackhome-bucket