spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: 6379
      password: 1234

    mongodb:
      username: root
      password: root
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin

  cloud:
    gcp:
      storage:
        bucket: comebackhome-bucket

  google:
    redirect_uri: "http://localhost:8085/login/oauth2/code/google"


