spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: 6379
      password: 1234

  cloud:
    gcp:
      storage:
        bucket: comebackhome-bucket