spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://34.122.128.155:3306/comebackhome?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: cbh123@
    driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    uris: http://elasticsearch:9200

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  data:
    redis:
      host: redis-refresh-token
      port: 6379
      password: 1234

  cloud:
    gcp:
      storage:
        bucket: comebackhome-bucket

  google:
    redirect_uri: "https://cbh.kro.kr/login/oauth2/code/google"