filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/data/*.log
      - /usr/share/filebeat/logs/error/*.log

output.elasticsearch:
  hosts: ["https://cbh.kro.kr/elasticsearch/"]
  protocol: "https"
  ssl.verification_mode: "full"