name: Build API Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Authenticate to GCP
        uses: google-github-actions/docker@v0.11.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # GitHub Secrets에 GCP 서비스 계정 키 추가

      - name: Configure Docker for GCP
        uses: google-github-actions/docker@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # GCP 프로젝트 ID

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-server .
          
      - name: Push Docker Image to GCP Artifact Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-server
