name: Build and Deploy API Server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Verify JAR File Exists
        run: |
          if [ ! -f build/libs/Comebackhome-be-0.0.1-SNAPSHOT.jar ]; then
            echo "❌ JAR 파일이 없습니다!"
            exit 1
          fi
          FILESIZE=$(stat -c%s "build/libs/Comebackhome-be-0.0.1-SNAPSHOT.jar")
          if [ "$FILESIZE" -lt 10000000 ]; then
            echo "❌ JAR 파일 용량이 너무 작습니다. 빌드 실패 가능성 있음."
            exit 1
          fi

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for GCP Artifact Registry
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          no-cache: true
          tags: asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend-main/backend-main:latest

      - name: Deploy to GCP VM via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            echo "✅ Pull latest Docker image"
            docker pull asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend-main/backend-main:latest

            echo "✅ Restart container with new image"
            docker-compose down
            docker-compose up -d --build
